currency:
  url: https://www.cbr.ru/scripts/XML_daily.asp

weather:
  api-key: 9d6ee26be92f4c49c153246a179d62b6
  url: https://api.openweathermap.org/data/2.5/weather?id=%s&APPID=%s&units=metric

server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database: default
    show-sql: true
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baseline-on-migrate: true